# 1번문제

#### [데이터불러오기] mysql에서 KOPO_PRIDUCT_VOLUME 불러와 oracle에 저장하기

In [6]:
# PANDAS 패키지 불러오기
import pandas as pd 
import pymysql 
from sqlalchemy import create_engine 
 
# DB 커넥션 열기
engine1 = create_engine('mysql+pymysql://root:P@ssw0rd@192.168.110.112:3306/kopo') 

# DB 테이블을 읽어 Data Frame 변수에 저장하기
customerData = pd.read_sql_query('SELECT * FROM KOPO_PRODUCT_VOLUME', engine1)

In [7]:
engine2 = create_engine('oracle+cx_oracle://kopo:kopo@192.168.110.112:1521/orcl') 
resultname='KOPO_PY_정경화_FINAL1'
customerData.to_sql(resultname, engine2, if_exists='replace', index=False)

In [ ]:
# customerData.to_sql(resultname, engine_oracle, if_exists = 'replace', index=False,
#                     dtype={"REGIONID": sqlalchemy.NVARCHAR(25),
#                            "PRODUCTGROUP": sqlalchemy.NVARCHAR(25),
#                            "YEARWEEK": sqlalchemy.NVARCHAR(40),
#                            "VOLUME": sqlalchemy.Float})

# 2번문제

#### [데이터조작하기] oracle에서 KOPO_PRODUCT_VOLUME을 불러온 후 2016년도 자료만 남기고 oracle에 KOPO_PY_이름_FINAL2로 저장하기

In [68]:
# DB 테이블을 읽어 Data Frame 변수에 저장하기
customerData2 = pd.read_sql_query('SELECT * FROM KOPO_PRODUCT_VOLUME', engine2)
answer1 = customerData2[(customerData2.yearweek.str[0:4] == "2016")]
answer1.head()

   regionid productgroup yearweek    volume
82      A01       ST0001   201605  661049.0
83      A01       ST0002   201605  231214.0
84      A01       ST0001   201603  531372.0
85      A01       ST0002   201603  152763.0
86      A01       ST0001   201601  651243.0

In [51]:
resultname2='KOPO_PY_정경화_FINAL2'
answer1.to_sql(resultname2, engine2, if_exists='replace', index=False)

In [ ]:
# 컬럼명을 대문자로 바꾸려면?
# customerData2.columns = [x.upper() for x in customerData2.columns]

# 3번문제(크롤링)

## 첫번째 방법

In [3]:
import pandas as pd
from sqlalchemy import create_engine 
import requests, bs4, pandas as pd, numpy as np
resp = requests.get('https://www.timeanddate.com/holidays/south-korea/')
resp.encoding='utf-8'
html=resp.text
bs = bs4.BeautifulSoup(html, 'html.parser')

In [4]:
lists=[]
alldfcontents=[]

In [5]:
columns=bs.select(' tr.head > th.sep' )
contents=bs.select(' tbody > tr ')
contents

[<tr class="c0" id="tr0"><th class="nw">Jan 1</th><td class="nw">Monday</td><td><a href="/holidays/southkorea/new-year-day">New Year's Day</a></td><td>National holiday</td></tr>,
 <tr class="c1" id="tr1"><th class="nw">Feb 9</th><td class="nw">Friday</td><td><a href="/holidays/southkorea/winter-olympics-2018">2018 Winter Olympics start</a></td><td>Observance</td></tr>,
 <tr class="c0" id="tr2"><th class="nw">Feb 14</th><td class="nw">Wednesday</td><td><a href="/holidays/southkorea/valentines-day">Valentine's Day</a></td><td>Observance</td></tr>,
 <tr class="c1" id="tr3"><th class="nw">Feb 15</th><td class="nw">Thursday</td><td><a href="/holidays/southkorea/seollal-holiday-1">Seollal Holiday</a></td><td>National holiday</td></tr>,
 <tr class="c0" id="tr4"><th class="nw">Feb 16</th><td class="nw">Friday</td><td><a href="/holidays/southkorea/seollal-holiday-2">Seollal</a></td><td>National holiday</td></tr>,
 <tr class="c1" id="tr5"><th class="nw">Feb 17</th><td class="nw">Saturday</td><td><a href="/holidays/southkorea/seollal-holiday-3">Seollal Holiday</a></td><td>National holiday</td></tr>,
 <tr class="c0" id="tr6"><th class="nw">Feb 25</th><td class="nw">Sunday</td><td><a href="/holidays/southkorea/winter-olympics-2018">2018 Winter Olympics end</a></td><td>Observance</td></tr>,
 <tr class="c1" id="tr7"><th class="nw">Mar 1</th><td class="nw">Thursday</td><td><a href="/holidays/southkorea/independence-movement-day">Independence Movement Day</a></td><td>National holiday</td></tr>,
 <tr class="c0" id="tr8"><th class="nw">Mar 9</th><td class="nw">Friday</td><td><a href="/holidays/southkorea/winter-paralympics-2018">2018 Winter Paralympics start</a></td><td>Observance</td></tr>,
 <tr class="c1" id="tr9"><th class="nw">Mar 18</th><td class="nw">Sunday</td><td><a href="/holidays/southkorea/winter-paralympics-2018">2018 Winter Paralympics end</a></td><td>Observance</td></tr>,
 <tr class="c0" id="tr10"><th class="nw">Mar 20</th><td class="nw">Tuesday</td><td><a href="/calendar/march-equinox.html">March equinox</a></td><td>Season</td></tr>,
 <tr class="c1" id="tr11"><th class="nw">Apr 5</th><td class="nw">Thursday</td><td><a href="/holidays/southkorea/arbor-day">Arbor Day</a></td><td>Observance</td></tr>,
 <tr class="c0" id="tr12"><th class="nw">May 1</th><td class="nw">Tuesday</td><td><a href="/holidays/southkorea/labor-day">Labor Day</a></td><td>Bank Holiday</td></tr>,
 <tr class="c1" id="tr13"><th class="nw">May 5</th><td class="nw">Saturday</td><td><a href="/holidays/southkorea/childrens-day">Children's Day</a></td><td>National holiday</td></tr>,
 <tr class="c0" id="tr14"><th class="nw">May 7</th><td class="nw">Monday</td><td><a href="/holidays/southkorea/childrens-day">Children's Day observed</a></td><td>National holiday</td></tr>,
 <tr class="c1" id="tr15"><th class="nw">May 8</th><td class="nw">Tuesday</td><td><a href="/holidays/southkorea/parents-day">Parents' Day</a></td><td>Observance</td></tr>,
 <tr class="c0" id="tr16"><th class="nw">May 15</th><td class="nw">Tuesday</td><td><a href="/holidays/southkorea/teachers-day">Teacher's Day</a></td><td>Observance</td></tr>,
 <tr class="c1" id="tr17"><th class="nw">May 22</th><td class="nw">Tuesday</td><td><a href="/holidays/southkorea/buddha-birthday">Buddha's Birthday</a></td><td>National holiday</td></tr>,
 <tr class="c0" id="tr18"><th class="nw">Jun 6</th><td class="nw">Wednesday</td><td><a href="/holidays/southkorea/memorial-day">Memorial Day</a></td><td>National holiday</td></tr>,
 <tr class="c1" id="tr19"><th class="nw">Jun 13</th><td class="nw">Wednesday</td><td><a href="/holidays/southkorea/local-election-day">Local Election Day</a></td><td>National holiday</td></tr>,
 <tr class="c0" id="tr20"><th class="nw">Jun 21</th><td class="nw">Thursday</td><td><a href="/calendar/june-solstice.html">June Solstice</a></td><td>Season</td></tr>,
 <tr class="c1" id="tr21"><th class="nw">Jul 17</th><td class="nw">Tuesday</td><td><a href="/holidays/southkorea/constitution-day">Constitution Day</a></td><td>Observance</td></tr>,
 <tr class="c0" id="tr22"><th class="nw">Aug 15</th><td class="nw">Wednesday</td><td><a href="/holidays/southkorea/liberation-day">Liberation Day</a></td><td>National holiday</td></tr>,
 <tr class="c1" id="tr23"><th class="nw">Sep 23</th><td class="nw">Sunday</td><td><a href="/calendar/september-equinox.html">September equinox</a></td><td>Season</td></tr>,
 <tr class="c0" id="tr24"><th class="nw">Sep 23</th><td class="nw">Sunday</td><td><a href="/holidays/southkorea/mid-autumn-festival-day-1">Chuseok Holiday</a></td><td>National holiday</td></tr>,
 <tr class="c1" id="tr25"><th class="nw">Sep 24</th><td class="nw">Monday</td><td><a href="/holidays/southkorea/mid-autumn-festival-day-2">Chuseok</a></td><td>National holiday</td></tr>,
 <tr class="c0" id="tr26"><th class="nw">Sep 25</th><td class="nw">Tuesday</td><td><a href="/holidays/southkorea/mid-autumn-festival-day-3">Chuseok Holiday</a></td><td>National holiday</td></tr>,
 <tr class="c1" id="tr27"><th class="nw">Sep 26</th><td class="nw">Wednesday</td><td><a href="/holidays/southkorea/mid-autumn-festival-day-4">Chuseok Holiday</a></td><td>National holiday</td></tr>,
 <tr class="c0" id="tr28"><th class="nw">Oct 1</th><td class="nw">Monday</td><td><a href="/holidays/southkorea/armed-forces-day">Armed Forces Day</a></td><td>Observance</td></tr>,
 <tr class="c1" id="tr29"><th class="nw">Oct 3</th><td class="nw">Wednesday</td><td><a href="/holidays/southkorea/national-foundation-day">National Foundation Day</a></td><td>National holiday</td></tr>,
 <tr class="c0" id="tr30"><th class="nw">Oct 9</th><td class="nw">Tuesday</td><td><a href="/holidays/southkorea/hangeul-day">Hangeul Proclamation Day</a></td><td>National holiday</td></tr>,
 <tr class="c1" id="tr31"><th class="nw">Oct 31</th><td class="nw">Wednesday</td><td><a href="/holidays/southkorea/halloween">Halloween</a></td><td>Observance</td></tr>,
 <tr class="c0" id="tr32"><th class="nw">Dec 21</th><td class="nw">Friday</td><td><a href="/calendar/december-solstice.html">December Solstice</a></td><td>Season</td></tr>,
 <tr class="c1" id="tr33"><th class="nw">Dec 24</th><td class="nw">Monday</td><td><a href="/holidays/southkorea/christmas-eve">Christmas Eve</a></td><td>Observance</td></tr>,
 <tr class="c0" id="tr34"><th class="nw">Dec 25</th><td class="nw">Tuesday</td><td><a href="/holidays/southkorea/christmas-day">Christmas Day</a></td><td>National holiday</td></tr>,
 <tr class="c1" id="tr35"><th class="nw">Dec 31</th><td class="nw">Monday</td><td><a href="/holidays/southkorea/new-year-eve">New Year's Eve</a></td><td>Observance</td></tr>]

In [6]:
columnlist=[]
for column in columns:
    columnlist.append(column.text)
columnlist

['Weekday', 'Holiday Name', 'Holiday Type']

In [7]:
for content in contents:
    tds=content.findAll("td")
    for num in tds:
        if(num.text=="None"):
            continue;
        lists.append(num.text)
    alldfcontents.append(lists)
    lists=[]
df=pd.DataFrame(data=alldfcontents)
df

            0                              1                 2
0      Monday                 New Year's Day  National holiday
1      Friday     2018 Winter Olympics start        Observance
2   Wednesday                Valentine's Day        Observance
3    Thursday                Seollal Holiday  National holiday
4      Friday                        Seollal  National holiday
5    Saturday                Seollal Holiday  National holiday
6      Sunday       2018 Winter Olympics end        Observance
7    Thursday      Independence Movement Day  National holiday
8      Friday  2018 Winter Paralympics start        Observance
9      Sunday    2018 Winter Paralympics end        Observance
10    Tuesday                  March equinox            Season
11   Thursday                      Arbor Day        Observance
12    Tuesday                      Labor Day      Bank Holiday
13   Saturday                 Children's Day  National holiday
14     Monday        Children's Day observed  National holiday
15    Tuesday                   Parents' Day        Observance
16    Tuesday                  Teacher's Day        Observance
17    Tuesday              Buddha's Birthday  National holiday
18  Wednesday                   Memorial Day  National holiday
19  Wednesday             Local Election Day  National holiday
20   Thursday                  June Solstice            Season
21    Tuesday               Constitution Day        Observance
22  Wednesday                 Liberation Day  National holiday
23     Sunday              September equinox            Season
24     Sunday                Chuseok Holiday  National holiday
25     Monday                        Chuseok  National holiday
26    Tuesday                Chuseok Holiday  National holiday
27  Wednesday                Chuseok Holiday  National holiday
28     Monday               Armed Forces Day        Observance
29  Wednesday        National Foundation Day  National holiday
30    Tuesday       Hangeul Proclamation Day  National holiday
31  Wednesday                      Halloween        Observance
32     Friday              December Solstice            Season
33     Monday                  Christmas Eve        Observance
34    Tuesday                  Christmas Day  National holiday
35     Monday                 New Year's Eve        Observance

In [8]:
columnslist1=["DATE"]
columnslist1

['DATE']

In [9]:
contents1=bs.select(' tbody > tr > th.nw ' )
contents1

[<th class="nw">Jan 1</th>,
 <th class="nw">Feb 9</th>,
 <th class="nw">Feb 14</th>,
 <th class="nw">Feb 15</th>,
 <th class="nw">Feb 16</th>,
 <th class="nw">Feb 17</th>,
 <th class="nw">Feb 25</th>,
 <th class="nw">Mar 1</th>,
 <th class="nw">Mar 9</th>,
 <th class="nw">Mar 18</th>,
 <th class="nw">Mar 20</th>,
 <th class="nw">Apr 5</th>,
 <th class="nw">May 1</th>,
 <th class="nw">May 5</th>,
 <th class="nw">May 7</th>,
 <th class="nw">May 8</th>,
 <th class="nw">May 15</th>,
 <th class="nw">May 22</th>,
 <th class="nw">Jun 6</th>,
 <th class="nw">Jun 13</th>,
 <th class="nw">Jun 21</th>,
 <th class="nw">Jul 17</th>,
 <th class="nw">Aug 15</th>,
 <th class="nw">Sep 23</th>,
 <th class="nw">Sep 23</th>,
 <th class="nw">Sep 24</th>,
 <th class="nw">Sep 25</th>,
 <th class="nw">Sep 26</th>,
 <th class="nw">Oct 1</th>,
 <th class="nw">Oct 3</th>,
 <th class="nw">Oct 9</th>,
 <th class="nw">Oct 31</th>,
 <th class="nw">Dec 21</th>,
 <th class="nw">Dec 24</th>,
 <th class="nw">Dec 25</th>,
 <th class="nw">Dec 31</th>]

In [10]:
lists1=[]
datelists=[]

for content in contents1:
    if(content.text=="None"):
         continue;
    lists1.append(content.text)
    datelists.append(lists1)
    lists1=[]
    
datelists

[['Jan 1'],
 ['Feb 9'],
 ['Feb 14'],
 ['Feb 15'],
 ['Feb 16'],
 ['Feb 17'],
 ['Feb 25'],
 ['Mar 1'],
 ['Mar 9'],
 ['Mar 18'],
 ['Mar 20'],
 ['Apr 5'],
 ['May 1'],
 ['May 5'],
 ['May 7'],
 ['May 8'],
 ['May 15'],
 ['May 22'],
 ['Jun 6'],
 ['Jun 13'],
 ['Jun 21'],
 ['Jul 17'],
 ['Aug 15'],
 ['Sep 23'],
 ['Sep 23'],
 ['Sep 24'],
 ['Sep 25'],
 ['Sep 26'],
 ['Oct 1'],
 ['Oct 3'],
 ['Oct 9'],
 ['Oct 31'],
 ['Dec 21'],
 ['Dec 24'],
 ['Dec 25'],
 ['Dec 31']]

In [11]:
result1=pd.DataFrame(columns=columnslist1, data=datelists )
result2=pd.DataFrame(columns=columnlist, data=alldfcontents )
result2.columns = ["WEEK","HOLIDAY_NAME","HOLIDAY_TYPE"]


finalresult = pd.concat([result1,result2], axis=1)
finalresult

      DATE       WEEK                   HOLIDAY_NAME      HOLIDAY_TYPE
0    Jan 1     Monday                 New Year's Day  National holiday
1    Feb 9     Friday     2018 Winter Olympics start        Observance
2   Feb 14  Wednesday                Valentine's Day        Observance
3   Feb 15   Thursday                Seollal Holiday  National holiday
4   Feb 16     Friday                        Seollal  National holiday
5   Feb 17   Saturday                Seollal Holiday  National holiday
6   Feb 25     Sunday       2018 Winter Olympics end        Observance
7    Mar 1   Thursday      Independence Movement Day  National holiday
8    Mar 9     Friday  2018 Winter Paralympics start        Observance
9   Mar 18     Sunday    2018 Winter Paralympics end        Observance
10  Mar 20    Tuesday                  March equinox            Season
11   Apr 5   Thursday                      Arbor Day        Observance
12   May 1    Tuesday                      Labor Day      Bank Holiday
13   May 5   Saturday                 Children's Day  National holiday
14   May 7     Monday        Children's Day observed  National holiday
15   May 8    Tuesday                   Parents' Day        Observance
16  May 15    Tuesday                  Teacher's Day        Observance
17  May 22    Tuesday              Buddha's Birthday  National holiday
18   Jun 6  Wednesday                   Memorial Day  National holiday
19  Jun 13  Wednesday             Local Election Day  National holiday
20  Jun 21   Thursday                  June Solstice            Season
21  Jul 17    Tuesday               Constitution Day        Observance
22  Aug 15  Wednesday                 Liberation Day  National holiday
23  Sep 23     Sunday              September equinox            Season
24  Sep 23     Sunday                Chuseok Holiday  National holiday
25  Sep 24     Monday                        Chuseok  National holiday
26  Sep 25    Tuesday                Chuseok Holiday  National holiday
27  Sep 26  Wednesday                Chuseok Holiday  National holiday
28   Oct 1     Monday               Armed Forces Day        Observance
29   Oct 3  Wednesday        National Foundation Day  National holiday
30   Oct 9    Tuesday       Hangeul Proclamation Day  National holiday
31  Oct 31  Wednesday                      Halloween        Observance
32  Dec 21     Friday              December Solstice            Season
33  Dec 24     Monday                  Christmas Eve        Observance
34  Dec 25    Tuesday                  Christmas Day  National holiday
35  Dec 31     Monday                 New Year's Eve        Observance

In [12]:
# DB 커넥션 열기
engine = create_engine('oracle+cx_oracle://kopo:kopo@192.168.110.112:1521/orcl') 

resultname='KOPO_PY_정경화_FINAL3'
finalresult.to_sql(resultname, engine, if_exists='replace', index=False)

## 두번째 방법(한꺼번에 불러오기)

In [1]:
import pandas as pd
from sqlalchemy import create_engine 
import requests, bs4, pandas as pd, numpy as np
resp = requests.get('https://www.timeanddate.com/holidays/south-korea/')
resp.encoding='utf-8'
html=resp.text
bs = bs4.BeautifulSoup(html, 'html.parser')

In [2]:
contents = bs.select('table > tbody > tr ')
dfcontent = []
alldfcontents= []

for content in contents:
    tds = content.select("th,td")
    for td in tds:
        if(td.text == "None"):
            continue;
        dfcontent.append(td.text)
    alldfcontents.append(dfcontent)
    dfcontent=[]
df=pd.DataFrame(data=alldfcontents)
df.columns=['DATE','WEEK','HOLIDAY_NAME','HOLIDAY_TYPE']

In [3]:
df.head(3)

     DATE       WEEK                HOLIDAY_NAME      HOLIDAY_TYPE
0   Jan 1     Monday              New Year's Day  National holiday
1   Feb 9     Friday  2018 Winter Olympics start        Observance
2  Feb 14  Wednesday             Valentine's Day        Observance